### ISSUE TITLE
В проекте циклическая зависимость между IChat library,IntExplorer library и Cossacks.Как это починить?

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [ereb-thanatos/cossacks-revamp-2017#1]
В проекте циклическая зависимость между IChat library,IntExplorer library и Cossacks.Как это починить?

**Comment by ivan-kulikov-dev** [comment]
И как я понял,Исходников AI нету и надо производить реверс инжиниринг AI или писать свой?

**Comment by ereb-thanatos** [comment]
Да, исходников ИИ у меня нет. Циклическая зависимость не представляет большой проблемы. В репозиторий я включил файл IChat.lib, позволяющий собрать dmcr.exe, а затем и всё остальное. Главное не пересобирать всё решение одновременно.
