### ISSUE TITLE
Вопросы по игре Казаки Снова война

### ISSUE THREAD

**Issue by Russianstory** [ereb-thanatos/cossacks-revamp-2017#10]
ereb-thanatos друг дорогой д\здорова!!!

**Comment by Russianstory** [comment]
Дело в том, что я сам делаю мод на Казаки СНова война. И кое-что может быть тебе будет интересно. Я к великому сожалению не умею кодить. Но мне очень нужна твоя помощь друг...

**Comment by ereb-thanatos** [comment]
Добрый день. К сожалению, я больше не занимаюсь этим проектом и не смогу помочь вам. Желаю удачи и успешного моддинга.
P.S.: Возможно, вам будет интересно взглянуть на #8

**Comment by Russianstory** [comment]
Блин дико жаль у меня почти всё готово но увидел вас

**Comment by Russianstory** [comment]
А ты умеешь вообще менять кнопки  и прочее? изменять ИИ в игре???
