### ISSUE TITLE
ЭРЕБ помоги вопросы есть Где можно с тобой поговорить (печатать)

### ISSUE THREAD

**Issue by Russianstory** [ereb-thanatos/cossacks-revamp-2017#11]
Эреб прошу помощи...

**Comment by Russianstory** [comment]
Эреб правда нужны твои совет /помощь ) очень надо )))

**Comment by ereb-thanatos** [comment]
Сожалею, но у меня нет возможности возобновить проект или оказывать помощь вам. Желаю удачи.

**Comment by alexeik** [comment]
@Russianstory , а что тыхочешь?
