### ISSUE TITLE
Перевод на русский язык

### ISSUE THREAD

**Issue by DelmorS** [ereb-thanatos/cossacks-revamp-2017#12]
Приветствую, не нашел как написать личное сообщение, поэтому пишу сюда.
Подскажите пожалуйста, есть ли у данной версии Казаков перевод на русский язык? Чтобы можно было играть с переведенными юнитами, апгрейдами.
Спасибо

**Comment by alexeik** [comment]
да, просто сделай так:
чтобы заработала 1.42 с русским переводом то:
после копирования 1.42 в папку с 1.35
нужно иметь ввиду, что 1.42 использует имя resources.gsc вместо all.gsc
1.42 идет с английским языком.
Поэтому удалите resources.gsc от 1.42 и переименуйте all.gsc в resources.gsc
и 1.42 будет русский.

**Comment by ICoderman** [comment]
Привет!
Полноценный перевод на Русский язык доступен в версии 1.52 от 2025 года.
https://github.com/ICoderman/cossacks-revamp-2025

**Comment by MisterCoderman** [comment]
Привет! В версии 1.52 уже встроен Русский язык.

https://github.com/MisterCoderman/cossacks-2025
