### ISSUE TITLE
Issue With AI In MP !

### ISSUE THREAD

**Issue by lixicus** [ereb-thanatos/cossacks-revamp-2017#14]
Played Online with a fried these past few days and upon trying to set the game settings for dock to only limit building boats, it bugs out and it seems that only the players are limited to the fishing boats, AI is still building battle boats even tough it's not supposed to do that. TL;RD : Ai is not abiding by the game rules set in the lobby.

**Comment by ereb-thanatos** [comment]
Hi,
the additional multiplayer options are implemented in a way that does not interfere with the existing AI. Simply put, the constraints are implemented by hiding the relevant unit production tiles in the user interface. This was the easiest way to do this without fear of breaking other things. Furthermore I do not have the source code for the AI libraries, therefore I can not easily change the AI behavior.
I hope that this is not a show stopper for you. Maybe you can view it like an additional challenge when playing against the AI ; )
