### ISSUE TITLE
Capture Options: No Centre or Peasant Captures bug

### ISSUE THREAD

**Issue by iMckify** [ereb-thanatos/cossacks-revamp-2017#18]
Bug appears when playing Multiplayer game with Capture Options: No Centre or Peasant Captures, peace time some Very Hard bots, everyone with an unique nation. Host player could not capture any peasant of the cpu, but somehow could capture joined player's single peasant, therefore build new buildings. Does this bug appear on the host player only? How could it even happen with the disabled capture option? Bug did apear on multiple Multiplayer games.

**Comment by ereb-thanatos** [comment]
Thanks for the bug report. Sadly I am no longer working on this project and will not be able to address this issue.

> Does this bug appear on the host player only? How could it even happen with the disabled capture option?

No idea. I was not aware of this bug during development. The *disable capture* option is part of the original game. I did not modify it in any way as far as I can remember.
