### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by KaesDingeling** [ereb-thanatos/cossacks-revamp-2017#19]
Thanks for your work.

After patching it I noticed that the patch also overwrites the language files of the game with an English version. I would like to see other languages added as well. In my case German. I guess that others would be happy if your national languages are supported as well.

**Comment by ereb-thanatos** [comment]
Thanks for the feedback.

> After patching it I noticed that the patch also overwrites [...]

Please note that this is **not** a patch. It is a complete release. A standalone mod, if you like.

>  I would like to see other languages added as well.

I can assure you that you are not alone. Sadly I had to drop the multi-language support. There were some issues that were most easily fixed through resource files, not game engine code. Hence I had to pack my own resource archive.

However, if you take a look at [this code](https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/3ba6178475e916b6edceacc5347e9d15d5582065/src/Main%20executable/Arc/GSCset.cpp#L299), you'll see that the game engine allows the user to place an ```override.gsc``` resource archive file in the game directory. The resources found in this file will be prioritized over the default ones. This allows you to grab one of the publicly available GSC tools and create a custom translation package by picking the relevant files from a German version of Cossacks.

If you succeed, please feel free to open a pull request with the resulting translation resource archive ; )

Viel Glück & Spaß am Spiel
Ereb

**Comment by KaesDingeling** [comment]
Thank you very much. I have long searched for the "GSC Tool" and also found something, but unfortunately nothing to download. Therefore my question if you could name a source?

**Comment by ereb-thanatos** [comment]
I did a quick search for **GSC File Utility** with the Russian search engine Yandex. Here are a few sites that feature download links:

> https://cossacks-portal.ru/load/ostalnoe/gsc_file_utility/2012-06-17
> http://cossacksworld.ucoz.co.uk/index/gsc_file_utility/0-175
> http://glc-forum.flybb.ru/topic29.html

A particularly promising one leads to a **GSC Tools Pack**:
> https://www.dropbox.com/s/dwg80fkuyv0ck6b/GSC%20TOOLS%20PACK.rar?dl=0

Note that I only verified that these links are alive. I did not check the actual executables. Please use AV protection or a sandbox when running executables from foreign shores : )

Good luck

**Comment by KaesDingeling** [comment]
Thank you very much. It took me a while to understand how to use the tool. Also, I created a script that allows you to get all the files for the .gsc file in the correct format, since you can't drag folders into it. You can find the script here [prepar_for_packing](https://github.com/KaesDingeling/cossacks-revamp-2017/blob/master/prepar_for_packing.sh)

I was able to create my own translation and it works for the most part. I do have a few things to add though.
Umlauts are displayed strangely. [override.zip](https://github.com/KaesDingeling/cossacks-revamp-2017/blob/master/override.zip)
The .gsc was unfortunately too large.

I noticed that there is no support for larger resolutions than 1080p in 16:9 format. Before the patch, 1440p resolution was still possible.

**Comment by ereb-thanatos** [comment]
Thank you very much for the translation file! I added a link to it to the readme file.

> I noticed that there is no support for larger resolutions than 1080p in 16:9 format. Before the patch, 1440p resolution was still possible.

Indeed. Sadly, the resolution handling in Cossacks is not up to par with modern RTS games. In Cossacks, the higher the resolution, the more of the game map you can see on your screen without scrolling. Hence players with high-resolution monitors gain an advantage over others. Therefore I decided to cap the resolution at 1080p. IMHO the game was never meant to run on 4K monitors anyway ; )

**Comment by vlad8599** [comment]
Is it safe to use Windows libraries for GSC Editor instead those that Windows 10 already have?
