### ISSUE TITLE
Приложите пожалуйста релиз

### ISSUE THREAD

**Issue by grebenyukaa** [ereb-thanatos/cossacks-revamp-2017#2]
Доброго времени суток.
Увидел на хабре последнюю часть статьи "Реверс-инжиниринг «Казаков»", заинтересовался, собрал, попробовать запустить и обнаружил, что сюда не выложены никакие ресурсные файлы.

Ссылку в статье на mega.nz заметил не сразу, и файл великоват - требует логина для скачивания, это не удобно да и заводить его не хочется.

Было бы замечательно, если бы вы сюда залили в том числе и все требуемые игрой ресурсы, или хотя бы выложили архив сюда как релиз, если что-то из этого представляется возможным.

И ещё было бы неплохо ссылки на всё остальное выложить здесь в readme.

Спасибо.

**Comment by ereb-thanatos** [comment]
Здравствуйте,

спасибо за интерес. Не совсем понял на счёт логина для скачивания. Файл **[доступен для всех](https://mega.nz/#!05FHzZCB!IRb68Y9mBNpvCwuUfNq3GZOBKNM5l4K5Z_Sd_i1jHU0)**, да и скорость там хорошая. Вставлять ссылки в readme или заливать ресурсы, думаю, не стоит. К тому же размер файла с ресурсами игры (а в них тоже были исправления, в частности апгрейды на камень) ненамного меньше всего архива с игрой.

Удачного кодинга!

**Comment by grebenyukaa** [comment]
Файл то доступен, но у них(mega.nz), как оказалось, есть квоты на скачивание - у меня остановилось где-то на 150 МБ и попросило залогиниться для продолжения.

Ладно, на том же форуме ниже была ссылка на яндекс диск от другого пользователя, с него скачать удалось. И sha-1 совпало, так что всё хорошо.

Но вообще, всё же было бы неплохо как-то оформить здесь ссылки на всё остальное, чтобы человек, который наткнется сразу на этот репозиторий в обход хабра (и постов на других ресурсах) имел представление, откуда взять всё остальное, необходимое для запуска игры.

**Comment by metjka** [comment]
https://github.com/ereb-thanatos/cossacks-revamp-2017/releases
Вот тут было бы неплохо выложить релиз

**Comment by ereb-thanatos** [comment]
Так и быть - сделано.
