### ISSUE TITLE
Add new unique units to nations in order to make the game more historically accurate.

### ISSUE THREAD

**Issue by GreenMouseFan** [ereb-thanatos/cossacks-revamp-2017#20]
Hi guys, remember the MOD1? It added a lot of unique units to existing nations. I think this would be a nice improvement to make the rushed game - feel complete. I suggest the fellowing unique and new units from MOD1 and Cossacks 3 DLCs to be added:

Algeria: Bashibozouk
Austria: 18c musketeer
Austria: Grenadier
Bavaria: Grenadier
Denmark: Grenadier
Netherlands: 18c musketeer
Netherlands: 18c dragoon
England: 17c pikeman
England: 17c musketeer
England: Rider
England: 17c dragoon
England: 18c musketeer
England: Grenadier
France: 17c pikeman
France: 17c musketeer
France: 18c musketeer
Hungary: Grenadier
Piedmont: 18c musketeer
Piedmont: 18c dragoon
Poland: 17c dragoon (Pospolite ruszenie)
Poland: Grenadier
Portugal: 18c musketeer
Portugal: 17c pikeman
Portugal: Volunteer
Prussia: Grenadier
Russia: 18c musketeer
Russia: Grenadier
Russia: Hussar
Sweden: 17c pikeman
Sweden: 17c musketeer
Sweden: 18c musketeer
Sweden: Grenadier
Sweden: 18c dragoon
Sweden: Hussar
Sweden: Light rider (Hakkapeliitta)
Spain: 18c dragoon
Spain: 17c pikeman (Cosolete)
Turkey: Ottoman (heavy) infantryman
Ukraine: Chaika ship
Venice: 17c musketeer
European 17c cannon (all nations except Algeria and Turkey)
Ottoman cannon (Algeria and Turkey)
Coastal defence cannon (all nations)

For the ones already present on the MOD1 the graphics could be juat copied straight from it, if there will be no licensing issues.
Or make new graphics for these units and as well as blood upon death to make them more consistent with original CS:EW units.

For Bavaria and Danmark, i think we should make new sprites for 18c musketeers and use old sprites for grenadiers

Still i'm not sure if Scotland from CS3: Guardians of the Highlands DLC has to be added but this will be not disscused in this issue.
![screen1](https://user-images.githubusercontent.com/80595517/111039641-ad5a4300-8461-11eb-8dd6-4869b74de1c6.jpg)
![screen2](https://user-images.githubusercontent.com/80595517/111039646-b3e8ba80-8461-11eb-8493-d9e1a4d58067.jpg)
![screen3](https://user-images.githubusercontent.com/80595517/111039655-bd722280-8461-11eb-8dab-cd12f2fa3389.jpg)
![screen39](https://user-images.githubusercontent.com/80595517/111039688-ec889400-8461-11eb-84f7-baa066885b10.jpg)

**Comment by GreenMouseFan** [comment]
Or why not just make a another stand-alone expansion pack for Cossacks 1 that will feature the 1.36 and 1.42 improvements, all the above new units, a new nation Scotland, new missions and campagins, and the OGG music. Just like what was done for Age of Empires 2 recently or make Cossacks 4 maybe.

**Comment by ereb-thanatos** [comment]
It is possible to mod this release by overwriting / extending the game resources archive. This includes any unit / nation definitions. Please see [this comment](https://github.com/ereb-thanatos/cossacks-revamp-2017/issues/19#issuecomment-745279577) for more details.
