### ISSUE TITLE
Add mission SDK

### ISSUE THREAD

**Issue by Nekun** [ereb-thanatos/cossacks-revamp-2017#22]
It's would be nice to include mission SDK (also known as "Scenario Tool") to the repo, especially if you have a more recent version.

https://nekun.cpunks.moe/ul/6_ScenarioTool.rar

**Comment by ereb-thanatos** [comment]
Thank you for your suggestion, but I do not maintain this repository any longer. I also do not recall working on any sources for the Scenario Tool.
