### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sheepo99** [ereb-thanatos/cossacks-revamp-2017#23]
Hello, you said the full source code for BtW was released back in 2002. Do you have a link for this? Under which license was this released?

Secondly, does this repo itself contain a full copy of the source code with added modifications? And is this version compatible with Baddog's Mod 1 for BtW?

Best regards

**Comment by ereb-thanatos** [comment]
Hello. It has been a few years and I do not have any details on the original source code. This repository contains *some* version of the Cossacks source code, including bug fixes and modifications listed in the readme. I do not know whether it is compatible with any other modifications.

**Comment by sheepo99** [comment]
I've tried to look for it, but I am assuming the original source release was made on the old GSC boards or some ukrainian website which no longer exists. I would like to know if it would be possible if you could help me at least track the license under which the code was released, because if it is GPL compatible then a version of the engine can be repackaged into Linux repositories.
