### ISSUE TITLE
Версия 1.42 вылетает на некоторых картах.

### ISSUE THREAD

**Issue by kr63** [ereb-thanatos/cossacks-revamp-2017#3]
[Вот ссылка на save с проблемной картой.](https://cloud.mail.ru/public/3WNT/fiFX919on)

**Comment by ereb-thanatos** [comment]
Спасибо за сообщение. К сожалению, на данный момент в мои планы не входит возвращаться к проекту «Казаки».

**Comment by ICoderman** [comment]
Приветствую!
Проблемы с вылетами исправлены в версии 1.52 
https://github.com/ICoderman/cossacks-revamp-2025

**Comment by MisterCoderman** [comment]
Проблема решена в версии 1.52
https://github.com/MisterCoderman/cossacks-2025
