### ISSUE TITLE
Water is black on minimap

### ISSUE THREAD

**Issue by Postremus** [ereb-thanatos/cossacks-revamp-2017#4]
Water is black on the minimap. Is this intended?

To reproduce:
- Create a new Random Map
- One enemy
- Set to contintent land type
- set ballon start option to "Ballon", so that the whole map is revelead

![image](https://user-images.githubusercontent.com/1223135/34436248-3a566522-ec94-11e7-87c8-654b8d139517.png)

**Comment by Postremus** [comment]
Okay, found the reason why the minimaps water is black:
https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/master/src/Main%20executable/3DMapEd.cpp#L649

Makes total sense. Blue enemies on the water weren't really visible before. 
Black enemies are always shown as yellow on the minimap, which isn't ideal (because black is not the same color as yellow),but after the initial confusion is gone, it should not matter anymore.

**Comment by ereb-thanatos** [comment]
You are right, the minimap colors were changed on purpose.

I had not that many colors to choose from, but I wanted the map, all 7 players and the selected units in white to be distinguishable, so I changed the water to black, the black player to yellow and the white player to salmon-pink.

If you want, you can play around with different color values yourself. Just un-comment [this block of testing code](https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/ce8bebc454c328da005b357c7aa3aadff6982071/src/Main%20executable/mapa.cpp#L2461) I added and you'll see a palette of available colors.

Good luck!
