### ISSUE TITLE
Разрешение 4К

### ISSUE THREAD

**Issue by GVG** [ereb-thanatos/cossacks-revamp-2017#6]
Приветствую! Почему в игре нету поддержки разрешений больше 1920x1080? Нашёл в коде ограничение, но так не понял сути комментария `//Also disable all resolutions above ~1920 px wide for fairness reasons`. fairness reasons?
Игра валится при больших разрешениях?

**Comment by ereb-thanatos** [comment]
Добрый день!
Игра работоспособна на больших разрешениях, я проверял до 3842x2160 включительно.

Решение поставить лимит [обусловлено](https://translate.google.com/#en/ru/fairness%20reasons) тем, что игрок с большим экраном получает ощутимое преимущество в обзоре и в командовании большими армиями. Движок Казаков не был рассчитан на 4K и, в отличии от, например, StarCraft II, не масштабирует интерфейс и не контролирует угол обзора игрока.

**Comment by GVG** [comment]
Спасибо!

**Comment by ICoderman** [comment]
Приветствую! Это ограничение было убрано в версии 1.52.
https://github.com/ICoderman/cossacks-revamp-2025

**Comment by MisterCoderman** [comment]
Приветствую!
Это ограничение убрано в версии 1.52
https://github.com/MisterCoderman/cossacks-2025
