### ISSUE TITLE
Изменение файла в версии 1.42

### ISSUE THREAD

**Issue by ClanFoxReaper** [ereb-thanatos/cossacks-revamp-2017#7]
Меня интересует одну вещь!

Я собирался добавить уровней апгрейда для добывании камня/дерева/еды в одном из файлов ***.nds . Использовал программу GSC File Utility для перепаковки файла. Запускаю игру, а эффекта ноль.

Знаю что вы не хотите возвращаться в проект, но у вопрос.

Как правильно назвать файл?

**Comment by ereb-thanatos** [comment]
Добрый день. Быстрый поиск а-ля `grep -Hinr stone | grep -i upgrade` находит [такой код](https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/master/src/Main%20executable/NewUpgrade.cpp#L1404):
```c
case 21://EFFECT_STONE
{
    int val = NT->StoneEff;
    UseValue( &val, NU->ValueType, NU->Value );
    if (400 < val)
    {
        val = 400;//just in case
    }
    NT->StoneEff = val;
}

```
Т.е. **не вся логика в скриптах**, есть ограничения и в исходниках самой игры. Вы не уточнили, что именно не работает, но код выше, например, не даст вашему апгрейду повысить скорость сбора камня, даже если у вас получится добавить его в интерфейс игры.

Удачи в моддинге.
